name = "NHANES2003"
version = "0.1.0"
license = "license"
author = "Joseph J. Bennett"
maintainer = "jbennett@jbennettconsulting.com"
copyright = "Copyright 2024, Joseph J. Bennett"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[dependencies]
stdlib = "*"
csv-fortran.git = "https://github.com/jbennett7/csv-fortran"
[dev-dependencies]
test-drive.git = "https://github.com/jbennett7/test-drive"
